
name = "DashChartEditor"
uuid = "1b08a953-4be3-4667-9a23-c7a8b84d7eb8"
authors = ["Bryan Schroeder <bryan.ri.schroeder@gmail.com>"]
version = "0.0.1a5"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
